// biome-ignore-all assist/source/organizeImports: the re-export blocks below are
// generated by scripts/gen-exports.mjs in directory order. Re-sorting them would make
// the file differ from its generator on every run.

/**
 * Public API surface of `@the_viveksingh/vivek-ui`.
 *
 * Components and their prop types only. Internal `hooks/` and `utils/` stay unexported
 * so they can be refactored without a major version bump, and `components/internal/`
 * is never re-exported.
 *
 * Charts live at the `./charts` subpath instead of here, so an app that never draws a
 * chart does not pull the chart code into its module graph at all.
 *
 * Everything after the marker is generated. Add a component by creating
 * `src/components/<name>/index.ts` and running `pnpm gen:exports` — CI runs the
 * generator with `--check`, so a component that is built but never exported fails the
 * build instead of silently shipping as dead code.
 */

// --- generated below by scripts/gen-exports.mjs; run `pnpm gen:exports` ---

export {
  Accordion,
  AccordionContent,
  type AccordionContentProps,
  AccordionItem,
  type AccordionItemProps,
  type AccordionProps,
  type AccordionSize,
  AccordionTrigger,
  type AccordionTriggerProps,
  type AccordionVariant,
} from './components/accordion'
export { Alert, type AlertProps } from './components/alert'
export {
  AnimatedCounter,
  type AnimatedCounterProps,
  type CounterFormat,
} from './components/animated-counter'
export { AspectRatio, type AspectRatioProps } from './components/aspect-ratio'
export { Avatar, type AvatarGroupProps, type AvatarProps } from './components/avatar'
export { Badge, type BadgeProps } from './components/badge'
export {
  BentoGrid,
  type BentoGridItemProps,
  type BentoGridProps,
  type ResponsiveSpan,
} from './components/bento-grid'
export { Box, type BoxProps } from './components/box'
export {
  Breadcrumb,
  type BreadcrumbItemData,
  type BreadcrumbItemProps,
  type BreadcrumbProps,
  type BreadcrumbSeparatorProps,
} from './components/breadcrumb'
export { Button, type ButtonProps } from './components/button'
export { ButtonGroup, type ButtonGroupProps } from './components/button-group'
export {
  Calendar,
  type CalendarProps,
  type CalendarRangeProps,
  type CalendarSelection,
  type CalendarSingleProps,
  type DateLocale,
  type DateRange,
  type DisabledDates,
  formatDate,
  parseISODate,
  toISODate,
  type WeekStart,
} from './components/calendar'
export { Card, type CardProps, type CardSlotProps } from './components/card'
export { Carousel, type CarouselProps } from './components/carousel'
export {
  ChatCodeBlock,
  type ChatCodeBlockHighlighter,
  type ChatCodeBlockProps,
} from './components/chat-code-block'
export { ChatInput, type ChatInputProps } from './components/chat-input'
export {
  ChatMessage,
  type ChatMessageProps,
  type ChatMessageRole,
  type ChatMessageStatus,
  type ChatMessageVariant,
} from './components/chat-message'
export {
  ChatThread,
  ChatThreadEmpty,
  type ChatThreadEmptyProps,
  type ChatThreadMessage,
  type ChatThreadProps,
} from './components/chat-thread'
export { Checkbox, type CheckboxProps } from './components/checkbox'
export { Chip, type ChipProps } from './components/chip'
export { Clock, type ClockProps } from './components/clock'
export { Code, type CodeProps } from './components/code'
export {
  Combobox,
  type ComboboxMultipleProps,
  type ComboboxOption,
  type ComboboxProps,
  type ComboboxSingleProps,
} from './components/combobox'
export {
  CommandPalette,
  type CommandPaletteEntry,
  type CommandPaletteGroup,
  type CommandPaletteItem,
  type CommandPaletteProps,
} from './components/command-palette'
export { Container, type ContainerProps } from './components/container'
export { CopyButton, type CopyButtonProps, type CopyState } from './components/copy-button'
export { Countdown, type CountdownProps, type CountdownUnit } from './components/countdown'
export { CTA, type CTAProps } from './components/cta'
export {
  type Column,
  type ColumnKey,
  DataTable,
  type DataTableLabels,
  type DataTableProps,
  type DataTableSort,
  type DataTableStatusInfo,
  type SelectionKey,
  type SortDirection,
  type SortValue,
} from './components/data-table'
export { DatePicker, type DatePickerProps } from './components/date-picker'
export { Divider, type DividerProps } from './components/divider'
export {
  Drawer,
  DrawerBody,
  DrawerCloseButton,
  type DrawerCloseButtonProps,
  type DrawerFocusRef,
  DrawerFooter,
  DrawerHeader,
  type DrawerProps,
  type DrawerSide,
  type DrawerSize,
  type DrawerSlotProps,
  DrawerTitle,
  type DrawerTitleProps,
} from './components/drawer'
export {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  type DropdownMenuCheckboxItemProps,
  DropdownMenuContent,
  type DropdownMenuContentProps,
  DropdownMenuItem,
  type DropdownMenuItemProps,
  DropdownMenuLabel,
  type DropdownMenuLabelProps,
  type DropdownMenuProps,
  DropdownMenuSeparator,
  type DropdownMenuSeparatorProps,
  DropdownMenuTrigger,
  type DropdownMenuTriggerProps,
} from './components/dropdown-menu'
export {
  type CellChange,
  type EditableColumn,
  type EditableColumnKey,
  EditableGrid,
  type EditableGridProps,
} from './components/editable-grid'
export { EmptyState, type EmptyStateProps, type EmptyStateSize } from './components/empty-state'
export { FAQ, type FaqItem, type FAQProps } from './components/faq'
export { type Feature, FeatureGrid, type FeatureGridProps } from './components/feature-grid'
export { Field, type FieldProps } from './components/field'
export { FileTree, type FileTreeProps, type TreeNode } from './components/file-tree'
export {
  type FileRejection,
  type FileRejectReason,
  FileUpload,
  type FileUploadProps,
  formatBytes,
  matchesAccept,
} from './components/file-upload'
export {
  Footer,
  type FooterColumn,
  type FooterLink,
  type FooterProps,
} from './components/footer'
export {
  Form,
  type FormErrors,
  type FormProps,
  type FormState,
  type FormValues,
} from './components/form'
export { Grid, type GridProps, type ResponsiveCols } from './components/grid'
export { Heading, type HeadingProps } from './components/heading'
export { Hero, type HeroProps } from './components/hero'
export {
  HoverCard,
  HoverCardContent,
  type HoverCardContentProps,
  type HoverCardProps,
  HoverCardTrigger,
  type HoverCardTriggerProps,
} from './components/hover-card'
export { IconButton, type IconButtonProps } from './components/icon-button'
export { Image, type ImageProps } from './components/image'
export { Input, type InputProps } from './components/input'
export {
  KanbanBoard,
  type KanbanBoardProps,
  type KanbanCard,
  type KanbanColumn,
  type KanbanMove,
} from './components/kanban-board'
export { Kbd, type KbdProps } from './components/kbd'
export { Label, type LabelProps } from './components/label'
export { type Logo, LogoCloud, type LogoCloudProps } from './components/logo-cloud'
export { MapEmbed, type MapEmbedProps, type MapProvider } from './components/map-embed'
export { Marquee, type MarqueeDirection, type MarqueeProps } from './components/marquee'
export {
  Modal,
  ModalBody,
  ModalCloseButton,
  type ModalCloseButtonProps,
  type ModalFocusRef,
  ModalFooter,
  ModalHeader,
  type ModalProps,
  type ModalSize,
  type ModalSlotProps,
  ModalTitle,
  type ModalTitleProps,
} from './components/modal'
export {
  Navbar,
  NavbarActions,
  type NavbarActionsProps,
  NavbarBrand,
  type NavbarBrandProps,
  NavbarLink,
  type NavbarLinkProps,
  NavbarLinks,
  type NavbarLinksProps,
  type NavbarProps,
  NavbarToggle,
  type NavbarToggleProps,
} from './components/navbar'
export {
  Newsletter,
  type NewsletterProps,
  type NewsletterStatus,
} from './components/newsletter'
export { NumberInput, type NumberInputProps } from './components/number-input'
export { OTPInput, type OTPInputProps } from './components/otp-input'
export {
  Pagination,
  type PaginationLabels,
  type PaginationProps,
} from './components/pagination'
export {
  PasswordInput,
  type PasswordInputProps,
  type PasswordRule,
  type PasswordStrengthLevel,
} from './components/password-input'
export {
  Popover,
  PopoverClose,
  type PopoverCloseProps,
  PopoverContent,
  type PopoverContentProps,
  type PopoverProps,
  PopoverTrigger,
  type PopoverTriggerProps,
} from './components/popover'
export { Portal, type PortalContainer, type PortalProps } from './components/portal'
export { Pricing, type PricingPlan, type PricingProps } from './components/pricing'
export { Progress, type ProgressProps } from './components/progress'
export { isSafeHref, Prose, type ProseLinkProps, type ProseProps } from './components/prose'
export {
  Radio,
  RadioGroup,
  type RadioGroupProps,
  type RadioOption,
  type RadioProps,
} from './components/radio-group'
export { Rating, type RatingProps } from './components/rating'
export { RelativeTime, type RelativeTimeProps } from './components/relative-time'
export {
  Scheduler,
  type SchedulerEvent,
  type SchedulerProps,
  type SchedulerResource,
} from './components/scheduler'
export { ScrollArea, type ScrollAreaProps } from './components/scroll-area'
export {
  type HeadingLevel,
  Section,
  type SectionHeaderProps,
  type SectionProps,
} from './components/section'
export { Segmented, type SegmentedOption, type SegmentedProps } from './components/segmented'
export { Select, type SelectOption, type SelectProps } from './components/select'
export {
  Sidebar,
  SidebarItem,
  type SidebarItemProps,
  type SidebarProps,
  SidebarSection,
  type SidebarSectionProps,
  SidebarToggle,
  type SidebarToggleProps,
} from './components/sidebar'
export { Skeleton, type SkeletonProps } from './components/skeleton'
export {
  Slider,
  type SliderMark,
  type SliderProps,
  type SliderRangeProps,
  type SliderSingleProps,
} from './components/slider'
export { Spinner, type SpinnerProps } from './components/spinner'
export {
  Flex,
  type FlexProps,
  Stack,
  type StackAlign,
  type StackGap,
  type StackJustify,
  type StackProps,
} from './components/stack'
export { type Stat, Stats, type StatsProps } from './components/stats'
export {
  type Step,
  Stepper,
  type StepperOrientation,
  type StepperProps,
  type StepStatus,
} from './components/stepper'
export { Switch, type SwitchProps } from './components/switch'
export {
  Table,
  type TableAlign,
  type TableCaptionProps,
  type TableCellProps,
  type TableContainerProps,
  type TableHeaderCellProps,
  type TableProps,
  type TableRowProps,
  type TableSectionProps,
  type TableSize,
} from './components/table'
export {
  Tabs,
  type TabsActivationMode,
  TabsList,
  type TabsListProps,
  type TabsOrientation,
  TabsPanel,
  type TabsPanelProps,
  TabsPanels,
  type TabsPanelsProps,
  type TabsProps,
  type TabsSize,
  TabsTab,
  type TabsTabProps,
  type TabsVariant,
} from './components/tabs'
export { TagInput, type TagInputProps, type TagRejectReason } from './components/tag-input'
export {
  type Testimonial,
  Testimonials,
  type TestimonialsProps,
} from './components/testimonials'
export { Text, type TextProps } from './components/text'
export { Textarea, type TextareaProps } from './components/textarea'
export {
  createThemeScript,
  DEFAULT_STORAGE_KEY,
  DEFAULT_THEME_ATTRIBUTE,
  type ResolvedTheme,
  type Theme,
  type ThemeContextValue,
  ThemeProvider,
  type ThemeProviderProps,
  themeScript,
  type ThemeScriptOptions,
  useTheme,
} from './components/theme-provider'
export {
  ThemeToggle,
  type ThemeToggleMode,
  type ThemeToggleProps,
} from './components/theme-toggle'
export {
  Timeline,
  type TimelineAlign,
  type TimelineItemProps,
  type TimelineOrientation,
  type TimelineProps,
  type TimelineStatus,
} from './components/timeline'
export {
  Toast,
  type ToastApi,
  type ToastOptions,
  type ToastPosition,
  type ToastProps,
  ToastProvider,
  type ToastProviderProps,
  type ToastRecord,
  type ToastTone,
  useToast,
} from './components/toast'
export { Tooltip, type TooltipProps, type TooltipTriggerProps } from './components/tooltip'
export { TypingIndicator, type TypingIndicatorProps } from './components/typing-indicator'
export { VirtualList, type VirtualListProps } from './components/virtual-list'
